In [1]:
import skfuzzy as fuzz

In [3]:
from sklearn import datasets
from sklearn.cluster import KMeans
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn.metrics as sm

iris = datasets.load_iris()

x = pd.DataFrame(iris.data, columns=['Sepal Length', 'Sepal Width', 'Petal Length', 'Petal Width'])
y = pd.DataFrame(iris.target, columns=['Target'])

In [4]:
x

Sepal Length  Sepal Width  Petal Length  Petal Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [5]:
y

Target
0         0
1         0
2         0
3         0
4         0
..      ...
145       2
146       2
147       2
148       2
149       2

[150 rows x 1 columns]

In [6]:
xalldata = np.vstack((x['Sepal Length'], x['Sepal Width'], x['Petal Length'], x['Petal Width']))

In [7]:
xalldata

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       

In [8]:
cntr, u, u0, d, jm, p, fpc = fuzz.cluster.cmeans(xalldata, 4, 2, error=0.005, maxiter=1000,init=None, seed=None)

In [9]:
fpc

0.70678931724785

In [10]:
cntr

array([[5.0006524 , 3.41875629, 1.46992368, 0.24739632],
       [6.25417172, 2.88537418, 4.90794428, 1.69159591],
       [5.63723054, 2.65523621, 4.0235557 , 1.2414931 ],
       [6.99746913, 3.10343556, 5.88844163, 2.11876283]])

In [11]:
help(fpc)

Help on float64 object:

class float64(floating, builtins.float)
 |  float64(x=0, /)
 |  
 |  Double-precision floating-point number type, compatible with Python `float`
 |  and C ``double``.
 |  Character code: ``'d'``.
 |  Canonical name: ``np.double``.
 |  Alias: ``np.float_``.
 |  Alias *on this platform*: ``np.float64``: 64-bit precision floating-point number type: sign bit, 11 bits exponent, 52 bits mantissa.
 |  
 |  Method resolution order:
 |      float64
 |      floating
 |      inexact
 |      number
 |      generic
 |      builtins.float
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//v

In [14]:
u[1][149]

0.8191650112027068

In [13]:
u0[2][149]

0.5074310576485158

In [15]:
p

28

In [16]:
jm

array([219.72536372, 170.06124609, 167.39361744, 147.10378546,
        83.92872174,  54.73677713,  47.57656805,  44.36779163,
        42.87770429,  42.21898408,  41.92171493,  41.77921301,
        41.70643045,  41.6672834 ,  41.64540278,  41.63282722,
        41.62545086,  41.62105818,  41.61841228,  41.61680459,
        41.61582115,  41.61521644,  41.6148431 ,  41.61461187,
        41.61446831,  41.614379  ,  41.61432335,  41.61428864])

In [17]:
d

array([[0.15364315, 0.4388889 , 0.4115418 , 0.51505234, 0.1999636 ,
        0.68359126, 0.4105248 , 0.05918801, 0.79813979, 0.36656069,
        0.49165793, 0.24449835, 0.49217194, 0.90820693, 1.0256247 ,
        1.21495627, 0.66575968, 0.15532853, 0.8307443 , 0.39860813,
        0.46369368, 0.33639328, 0.64532651, 0.37512229, 0.47731042,
        0.4410482 , 0.20139502, 0.22246573, 0.21731773, 0.39675237,
        0.40128945, 0.42897875, 0.72557751, 0.93103463, 0.33895055,
        0.35065645, 0.53578823, 0.26380899, 0.75316705, 0.11564056,
        0.19555606, 1.23851107, 0.66314259, 0.3845129 , 0.60288493,
        0.47251951, 0.41759187, 0.46423313, 0.4145576 , 0.1457368 ,
        3.97581858, 3.57161119, 4.12838545, 3.00170357, 3.74129607,
        3.3408507 , 3.73702247, 2.22791089, 3.70572167, 2.79107797,
        2.58853086, 3.1633077 , 3.07437164, 3.63862082, 2.50470063,
        3.59210667, 3.35930839, 2.93926537, 3.69786155, 2.7992025 ,
        3.78901925, 3.01673419, 3.98332234, 3.59